// WARNING: DO NOT EDIT.  This file is automatically generated
// Written by aws-amplify-serverless-plugin/1.4.1 on 2021-11-08T17:37:37.873Z

const awsmobile = {
    aws_appsync_authenticationType: 'AMAZON_COGNITO_USER_POOLS',
    aws_appsync_graphqlEndpoint: 'https://jnoecnunojhzdbr2zpwj2vjd64.appsync-api.us-east-1.amazonaws.com/graphql',
    aws_appsync_region: 'us-east-1',
    aws_cognito_region: 'us-east-1',
    aws_project_region: 'us-east-1',
    aws_user_pools_id: 'us-east-1_Gmmqbdhie',
    aws_user_pools_web_client_id: '70681titoqu1dq7ho24j8h180o'
};

export default awsmobile;
